### ISSUE TITLE
typo in datetime __eq__ function

### ISSUE THREAD

**Issue by farzadab** [slashmili/python-jalali#11]
in line 761 of __init.py__ at the end of line is written:
    self.tzinfo == self.other_datetime.tzinfo
which should be:
    self.tzinfo == other_datetime.tzinfo

--------------
edit:
the problem is bigger than that. in the same function, there's a logical problem. if two datetime values have equal date but not equal time of day, they are suppose to be equal and vice versa (if time of the day is equal, they are supposed to be equal) but that is obviously flawed.

p.s: i saw another bug similiar to this one in datetime.__gt__, i will write an issue for that later

**Comment by slashmili** [comment]
fixed
