### ISSUE TITLE
X-Content-Type-Options

### ISSUE THREAD

**Issue by dj1372** [slashmili/python-jalali#129]
# Please include your runtime information

* jdatetime version:4.1
* Python version:3.9
* OS: ubuntu
سلام 
بنظر می آید پس از بروز رسانی اخیر فایل های js به درستی دریافت نمی شود و پیام خطای زیر را داریم:
/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc-fa.js" وجود ندارد 
The resource from “https://webops.ir/static/admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc-fa.js” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).

سابق بر این بدرستی استفاده میشده است. اخیرا این مشکل دیده شده
با احترام

**Comment by hramezani** [comment]
Hi,
Did you see this problem after upgrading django-jalali to 4.1?
Have you run the `collectstatics` management command?
Have you tested older versions?

**Comment by hramezani** [comment]
به نظر مشکلی از سمت لایبرری نیست. به نظر میرسه فایل مورد اشاره تو سرور وجود نداره یا به هر دلیلی در دسترس وب سرور نیست.
مثلا میتونه مشکل مجوزهای فایل باشه.

**Comment by hramezani** [comment]
خواهش میکنم.
بله روال نصب این هست. ولی محیط نصب ممکن هست متفاوت باشه.
به نظر مشکل از نصب نیست.
لطفا خطا رو در اینترنت جستجو کنید ممکن هست بتونید به نتیجه برسید
