### ISSUE TITLE
datetime and jdatetime pass diffrent returns

### ISSUE THREAD

**Issue by MohammadSafaeii** [slashmili/python-jalali#131]
in `datetime` library, `%%` counts as `% char`
so `datetime.now().strftime('%%d')` returns `'%d'` and don't consider %d as date number
but `jdatetime` will replace every `%d` in string
therefore `jdatetime.datetime.now().strftime('%%d')` returns `'%08'`

we can use more % 
for example  `datetime.now().strftime('%%%%%%d')` returns `'%%%d'`
but `jdatetime.datetime.now().strftime('%%%%%%d')` returns `'%%%%%08'`

`datetime.now().strftime('%%%%%d')` returns `'%%29'`
`jdatetime.datetime.now().strftime('%%%%%d')` returns `'%%%%08'`

**Comment by hramezani** [comment]
@MohammadSafaeii Thanks for reporting.
Yes, you are right we are not consistent here and it has to be fixed.

Do you have any solution? Would you like to work on it and prepare a patch?

**Comment by MohammadSafaeii** [comment]
I tried to replace every % with %%
then use this regex ([^%-]((%%)*)-?)({posix_list[i]}) but it still have some bugs and i couldn't handle it with regex
datetime checks string's characters 1 by 1 in loop,  i think its better solution

**Comment by slashmili** [comment]
@MohammadSafaeii it's fixed in the main. I'll publish the fix in the next days
