### ISSUE TITLE
The problem of 2124/03/20

### ISSUE THREAD

**Issue by eshahrvand** [slashmili/python-jalali#152]
# Please include your runtime information

* jdatetime version: 4.1.1
* Python version: 3.11.5
* OS: alpine3.18

Problem:
The Gregorian date 2124/03/20 must be 1503/01/01 in the Jalali calendar but this lib returns 1502/12/30.

Checks:
The Gregorian date 2025/03/20 must be 1403/12/30 in the Jalali calendar which currently is correct but must be rechecked after fixing the reported problem.

**Comment by slashmili** [comment]
Thanks for reporting the issue!

```python
>>> import jdatetime
>>> import datetime
>>> date = datetime.date(2124, 3, 20)
>>> jdatetime.date.fromgregorian(date=date)
jdatetime.date(1502, 12, 30)
>>>
```

Just part of the technicality, we are in a process of separating the date conversion to another package [jalali-core](https://github.com/slashmili/jalali-core) I'll create another issue on `jalali-core` as well.

**Comment by slashmili** [comment]
So it's hard for me to know the real date in far future, I tried it on time.ir and return the same result. It could be that both are wrong!
<img width="969" alt="Screenshot 2024-03-25 at 14 22 05" src="https://github.com/slashmili/python-jalali/assets/585764/9c75390f-bbe5-4a9b-8f5b-12be1a42157d">

However if I try using [jcal](http://savannah.nongnu.org/projects/jcal/): 
```
jdate --jalali=2124/03/20
Dos Far 01 00:00:00 CET 1503
```

**Comment by roozbehp** [comment]
jcal seems to be using the 2820-year cycle which should return incorrect results for as soon as the end of 1403 AP (this year). What does it return for 2025-03-20?

**Comment by slashmili** [comment]
Thanks @roozbehp for looking into that, you are correct:


so this lib returns:
```python
>>> date = datetime.date(2025, 3, 20)
>>> jdatetime.date.fromgregorian(date=date)
jdatetime.date(1403, 12, 30)
```


and jcal:
```
date --jalali=2025/03/20
Pan Far 01 00:00:00 CET 1404
```

@eshahrvand what was your rationale behind thinking that 2124-03-20 must be 1503-01-01 in the Jalali calendar?

**Comment by roozbehp** [comment]
> what was your rationale behind thinking that 2124-03-20 must be 1503-01-01 in the Hejri Shamis calendar?

There is no specific rationale. The 2820-year cycle algorithm implemented in jcal is an approximation of the actual astronomical calendar used on the ground, and so is the 33-year cycle implemented in jalali.py. Each make some mistakes in the estimation and are correct most other times. That's the nature of arithmetic approximations.

If you want actual astronomical calculations, here is the Python code to do that, which returns the best known estimate of the actual Persian calendar used in Iran. It's not written for production environments though, which makes it relatively slow:
https://github.com/roozbehp/persiancalendar

I have some long term plans to convert the output of this code to tables and implement a fast version usable in production, but I don't have any estimates for when that might happen.

**Comment by roozbehp** [comment]
(Edited my comment above. I had misunderstood the question originally.)

**Comment by roozbehp** [comment]
I have just implemented a fast Python version that works correctly from 1187 to 3000 AP (Hejri Shamsi). You can probably replace jalali-core with it easily. Here's the code (licensed under Apache 2.0 license, which is much less restrictive than LGPL):
https://github.com/roozbehp/persiancalendar/blob/main/persiancalendar_fast.py

If you want to convert between Gregorian and Persian calendars, you can copy the methods `fixed_from_gregorian()` and `gregorian_from_fixed()` from `persiancalendar.py` in the same project, but you can avoid all that hassle by using Python's `datetime.date.toordinal()` and `datetime.date.fromordinal()` instead.

I can help in adapting the code and reviewing changes.

**Comment by 5j9** [comment]
In case anyone else is curious, I did some [performance comparisons](https://github.com/5j9/persiancalendar/blob/09cbd454f1e5c46156d6e7ca835e2a590e84f5e0/benchmark.py) on a minorly modified version of `persiancalendar`  and my results were as follows:

* `persiancalendar_fast.persian_fast_from_fixed` was around 32% faster than `jalali_core.GregorianToJalali`.
* `persiancalendar_fast.persian_fast_from_fixed` was around 3% faster than `gshconverter.gregorian_to_solar_hijri`.

* `persiancalendar_fast.fixed_from_persian_fast` was around 60% faster than `jalali_core.JalaliToGregorian`.
* `persiancalendar_fast.fixed_from_persian_fast` was around 37%  *slower* than `gshconverter.solar_hijri_to_gregorian`.

P.S.
* The results are not very accurate and may vary by 10-20% in each run. I tried to choose median values.
* The tests where ran using Python 3.12.
* [`gshconverter`](https://github.com/5j9/gshconverter) is my own library, its output matches `jalali_core`.

**Comment by roozbehp** [comment]
Thanks. I've definitely not tried to optimize the code for speed yet. It's mostly optimized for readability. There are many speed optimizations I can think of. The name "fast" is chosen for comparison to the astronomical implementation, which is quite slow.

**Comment by slashmili** [comment]
I'll close this ticket and continue discussing `persiancalendar_fast` in [jalali-core repo](https://github.com/slashmili/jalali-core/issues/3)


@eshahrvand since I have not received any feedback from I'll close this ticket.
