### ISSUE TITLE
No such file or directory: 'README.rst' while installing

### ISSUE THREAD

**Issue by svenstaro** [slashmili/python-jalali#22]
So I do `pip install jdatetime` and it fails with `No such file or directory: 'README.rst'`

Probably just an oversight while doing the new release. :)

**Comment by slashmili** [comment]
Why did you close the pull request?

**Comment by svenstaro** [comment]
I didn't make a pull request.

**Comment by slashmili** [comment]
Ow Someone else did https://github.com/slashmili/python-jalali/pull/23 :)

But doesn't solve the problem, I'll fix it ASAP

**Comment by slashmili** [comment]
Problem should be fixed know
