### ISSUE TITLE
to specify format language manually

### ISSUE THREAD

**Issue by khafan246** [slashmili/python-jalali#24]
currently, the ```strftime``` depends on ```getdefaultlocale``` for language detection.
but this will not cover many use cases. it would be good to be able to specify it manually.

**Comment by slashmili** [comment]
The idea is to keep the `datetime` module function as they are in standard library.

Why don't you use locale to change the language?

**Comment by khafan246** [comment]
I don't get your point, changing locale will not affect the output:
```py
>>> import jdatetime
>>> d = jdatetime.datetime.now()
>>> print(d)
Yek, 05 Ord 1395 21:39:58
>>> import locale
>>> locale.setlocale(locale.LC_TIME, "fa_IR")
'fa_IR'
>>> print(d)
Yek, 05 Ord 1395 21:39:58
```
