### ISSUE TITLE
Support for locale

### ISSUE THREAD

**Issue by slashmili** [slashmili/python-jalali#26]
This is how python standard library works with `fa_IR` locale

```python
>> import locale
>> locale.setlocale(locale.LC_TIME, "fa_IR")
'fa_IR'
>>> import time
>> print time.strftime("%a, %d %b %Y %H:%M:%S")
'یکشنبه, 24 آوریل 2016 07:46:09'
>> datetime.datetime.now().strftime("%a, %d %b %Y %H:%M:%S")
'\xdb\x8c\xda\xa9\xd8\xb4\xd9\x86\xd8\xa8\xd9\x87, 24 \xd8\xa2\xd9\x88\xd8\xb1\xdb\x8c\xd9\x84 2016 07:47:10'
```

**Comment by khafan246** [comment]
currently, changing locale is not affecting output, as jdatetime depends on [getdefaultlocale](https://github.com/slashmili/python-jalali/blob/master/jdatetime/__init__.py#L118)
see another [issue](https://github.com/slashmili/python-jalali/issues/24#issuecomment-214003606)

**Comment by slashmili** [comment]
Correct, I need to change it so it works like the `datetime` module

**Comment by slashmili** [comment]
The change is in #27

**Comment by slashmili** [comment]
PR #27 has been merged to master
