### ISSUE TITLE
Support timezone in strptime

### ISSUE THREAD

**Issue by slashmili** [slashmili/python-jalali#53]
We would like to support `%z` in `jdatetime.datetime.strptime` function

Current behaviour of original `datetime`:
```python
date_string = "2019-6-6 12:13:14+0200"
date_format = "%Y-%m-%d %H:%M:%S%z"
datetime.datetime.strptime(date_string, date_format)
> datetime.datetime(2019, 6, 6, 12, 13, 14, tzinfo=datetime.timezone(datetime.timedelta(seconds=7200)))
date_string = "2019-6-6 01:13:14-0200"
date_format = "%Y-%m-%d %H:%M:%S%z"
datetime.datetime.strptime(date_string, date_format)
> datetime.datetime(2019, 6, 6, 1, 13, 14, tzinfo=datetime.timezone(datetime.timedelta(days=-1, seconds=79200)))
```

**Comment by Mojtaba-saf** [comment]
I want to start working on this issue.
at the moment python [doc ](https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes)accepts %z as follows:

> UTC offset in the form ±HHMM[SS[.ffffff]] (empty string if the object is naive).

and it is using this pattern.
`'z': r"(?P<z>[+-]\d\d:?[0-5]\d(:?[0-5]\d(\.\d{1,6})?)?|(?-i:Z))"`

I think it detect %Z in this pattern and we can remove that part to make it like this:
`'z': r"(?P<z>[+-]\d\d:?[0-5]\d(:?[0-5]\d(\.\d{1,6})?)?"`
and now just do what `datetime` is doing to calculate timezone offset:
```
if z[3] == ':':
    z = z[:3] + z[4:]
    if len(z) > 5:
        if z[5] != ':':
            msg = f"Inconsistent use of : in {found_dict['z']}"
            raise ValueError(msg)
        z = z[:5] + z[6:]
hours = int(z[1:3])
minutes = int(z[3:5])
seconds = int(z[5:7] or 0)
gmtoff = (hours * 60 * 60) + (minutes * 60) + seconds
gmtoff_remainder = z[8:]
# Pad to always return microseconds.
gmtoff_remainder_padding = "0" * (6 - len(gmtoff_remainder))
gmtoff_fraction = int(gmtoff_remainder + gmtoff_remainder_padding)
if z.startswith("-"):
    gmtoff = -gmtoff
    gmtoff_fraction = -gmtoff_fraction
```
I copied it from `datetime` and haven't tested it. it might need edit to be adjusted to this issue.
I'm open to suggestions.

**Comment by Mojtaba-saf** [comment]
@slashmili the class that handles RE are [here](https://github.com/python/cpython/blob/6f1efd19a70839d480e4b1fcd9fecd3a8725824b/Lib/_strptime.py#L170)
and [here](https://github.com/python/cpython/blob/6f1efd19a70839d480e4b1fcd9fecd3a8725824b/Lib/_strptime.py#L448) is start of how it handles z directive.

**Comment by slashmili** [comment]
deployed as part of [v4.1.0](https://github.com/slashmili/python-jalali/releases/tag/v4.1.0)
