### ISSUE TITLE
how can i get yesterday

### ISSUE THREAD

**Issue by saeedsafavi26** [slashmili/python-jalali#61]
hello, i use bellow code to code to get today's jalali date:
jdatetime.datetime.now().strftime("%Y %m %d")
how can i get yesteday in above format??

**Comment by farzadghanei** [comment]
@saeedsafavi26 this is a usage question, not a library issue. QA forums like [StackOverflow](https://stackoverflow.com) are better options than here.
`jdatetime` implements the same interface as Python standard library [datetime](https://docs.python.org/2/library/datetime.html), so the [same operations apply to it](https://stackoverflow.com/questions/30483977/python-get-yesterdays-date-as-a-string-in-yyyy-mm-dd-format/30484112).

```python
>>> from jdatetime import datetime, timedelta
>>> datetime.now() - timedelta(days=1)
jdatetime.datetime(1398, 7, 2, 16, 53, 26, 558957)
```
