### ISSUE TITLE
Compatibility with Matplotlib

### ISSUE THREAD

**Issue by minaee** [slashmili/python-jalali#68]
I am using `jdatetime` to convert the index of my `dataframe` to jalali calendar.

Then I want to `scatter` that `dataframe` as following:

    self.canvas.axes.scatter(df_day.index.values, df_day.loc[:, item], linestyle="None", marker='.')

> self.canvas.axes.scatter(df_day.index.values, df_day.loc[:, item], linestyle="None", marker='.')
>   File "/home/shahriar/.local/lib/python3.6/site-packages/matplotlib/__init__.py", line 1565, in inner
>     return func(ax, *map(sanitize_sequence, args), **kwargs)
>   File "/home/shahriar/.local/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py", line 358, in wrapper
>     return func(*args, **kwargs)
>   File "/home/shahriar/.local/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 4440, in scatter
>     alpha=alpha
>   File "/home/shahriar/.local/lib/python3.6/site-packages/matplotlib/collections.py", line 911, in __init__
>     Collection.__init__(self, **kwargs)
>   File "/home/shahriar/.local/lib/python3.6/site-packages/matplotlib/collections.py", line 153, in __init__
>     offsets = np.asanyarray(offsets, float)
>   File "/usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py", line 138, in asanyarray
>     return array(a, dtype, copy=False, order=order, subok=True)
> TypeError: float() argument must be a string or a number, not 'datetime'
> 
> Process finished with exit code 1
> 

any ideas how to solve it?

**Comment by farzadghanei** [comment]
This is a question about debugging a usage of `jdatetime`. GitHub Issues are the way to communicate about issues with `jdatetime` itself, for example when some code is using `jdatetime` and the behavior is unexpected, due to an bug in `jdatetime`, or when some feature is missing.

Other QA platforms such as [StackOverflow.com](https://stackoverflow.com/) or programming forums are proper channels of getting help about your application.

**Comment by minaee** [comment]
> This is a question about debugging a usage of `jdatetime`. GitHub Issues are the way to communicate about issues with `jdatetime` itself, for example when some code is using `jdatetime` and the behavior is unexpected, due to a bug in `jdatetime`, or when some feature is missing.
> 
> Other QA platforms such as [StackOverflow.com](https://stackoverflow.com/) or programming forums are proper channels of getting help about your application.
> 
> In this case, the issue seems more related to the contents of the dataframe (`df_day`).
> 
> ```
> File "/usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py", line 138, in asanyarray
> return array(a, dtype, copy=False, order=order, subok=True)
> ```
> 
> suggests a variable passed to the numpy function `asanarray`, was supposed to be a float value (or something that could convert to a float), but instead it's a `datetime` object.

Thank you for your clarification. But, being compatible with `matplotlib` isn't a missing feature?
Before the conversion, the type of index was 
    
    df_day.index.values type: 
         <class 'numpy.datetime64'>
    df_day.index.values: 
        2018-06-03T10:59:00.000000000
    df_day.index type: 
        <class 'pandas.core.indexes.datetimes.DatetimeIndex'>
    df_day.index: 
         DatetimeIndex(['2018-06-03 10:59:00', '2018-06-03 11:01:00',
               '2018-06-03 11:02:00', '2018-06-03 11:03:00',
               '2018-06-03 11:04:00', '2018-06-03 11:05:00',
               '2018-06-03 11:06:00', '2018-06-03 11:08:00',
               '2018-06-03 11:09:00', '2018-06-03 11:10:00',
               ...
               '2018-06-04 10:39:00', '2018-06-04 10:40:00',
               '2018-06-04 10:42:00', '2018-06-04 10:43:00',
               '2018-06-04 10:44:00', '2018-06-04 10:45:00',
               '2018-06-04 10:46:00', '2018-06-04 10:47:00',
               '2018-06-04 10:49:00', '2018-06-04 10:50:00'],
              dtype='datetime64[ns]', name='Timestamp', length=1227, freq=None)


When I pass converted `jdatetime' to scatter function these values are:

    df_day.index.values type: 
        <class 'jdatetime.datetime'>
    df_day.index.values: 
         1397-03-13 10:59:00
    df_day.index type: 
         <class 'pandas.core.indexes.base.Index'>
    df_day.index: 
        Index([1397-03-13 10:59:00, 1397-03-13 11:01:00, 1397-03-13 11:02:00,
           1397-03-13 11:03:00, 1397-03-13 11:04:00, 1397-03-13 11:05:00,
           1397-03-13 11:06:00, 1397-03-13 11:08:00, 1397-03-13 11:09:00,
           1397-03-13 11:10:00,
       ...
           1397-03-14 10:39:00, 1397-03-14 10:40:00, 1397-03-14 10:42:00,
           1397-03-14 10:43:00, 1397-03-14 10:44:00, 1397-03-14 10:45:00,
           1397-03-14 10:46:00, 1397-03-14 10:47:00, 1397-03-14 10:49:00,
           1397-03-14 10:50:00],
          dtype='object', name='Timestamp', length=1227)

I mean even if I create a `datetime` object of converted `jalali` values, I am not able to use the functionality of `jdatetime` library which is showing months name's in `Persian` such as `فروردین` or it's abbreviated value such as `فرو`.

Any Idea is really helpful.

**Comment by farzadghanei** [comment]
To help make the problem clearer, let's focus on the root cause. It seems that the issue comes from how `numpy` treats `jdatetime` objects, different than Python's `datetime` and NumPy's `datetime64` typs.

This basic example shows that `numpy` can create an [array](https://numpy.org/doc/stable/reference/generated/numpy.array.html#numpy.array) from a list of strings, [datetime.datetime](https://docs.python.org/3/library/datetime.html#datetime-objects), and [numpy.datetime64](https://numpy.org/devdocs/reference/arrays.datetime.html#basic-datetimes) objects, however it can not create an `array` from a list of `jdatetime.datetime` objects.

```python
Python 2.7.18 (default, Apr 20 2020, 00:00:00) 
[GCC 9.3.1 20200408 (Red Hat 9.3.1-2)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> import jdatetime
>>> from datetime import datetime
>>> py_dt = datetime(2020, 8, 12)
>>> j_dt = jdatetime.datetime(2020, 8, 12)
>>> n_dt = np.datetime64('2020-08-12')
>>> py_dt
datetime.datetime(2020, 8, 12, 0, 0)
>>> j_dt
jdatetime.datetime(2020, 8, 12, 0, 0)
>>> n_dt
numpy.datetime64('2020-08-12')
>>> np.array([py_dt], dtype='datetime64')
array(['2020-08-12T00:00:00.000000'], dtype='datetime64[us]')
>>> np.array([n_dt], dtype='datetime64')
array(['2020-08-12'], dtype='datetime64[D]')
>>> np.array([j_dt], dtype='datetime64')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: Cannot cast datetime.datetime object from metadata [us] to  according to the rule 'same_kind'
>>> np.array(['2020-08-12'], dtype='datetime64')
array(['2020-08-12'], dtype='datetime64[D]')
```

1. Can you please confirm if this is the root cause?

2. In your example, if you use a list of `datetime.datetime` instead of `jdatetime.datetime`, would that prevent the reported error?

Also please note that in any kind of issue reporting, it's helpful to mention runtime details, like Python version, the platform (OS, arch), and version of related libraries (numpy, etc.), specially if the results could be different for those differences.

**Comment by minaee** [comment]
> To help make the problem clearer, let's focus on the root cause. It seems that the issue comes from how `numpy` treats `jdatetime` objects, different than Python's `datetime` and NumPy's `datetime64` typs.
> 
> This basic example shows that `numpy` can create an [array](https://numpy.org/doc/stable/reference/generated/numpy.array.html#numpy.array) from a list of strings, [datetime.datetime](https://docs.python.org/3/library/datetime.html#datetime-objects), and [numpy.datetime64](https://numpy.org/devdocs/reference/arrays.datetime.html#basic-datetimes) objects, however it can not create an `array` from a list of `jdatetime.datetime` objects.
> 
> ```python
> Python 2.7.18 (default, Apr 20 2020, 00:00:00) 
> [GCC 9.3.1 20200408 (Red Hat 9.3.1-2)] on linux2
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import numpy as np
> >>> import jdatetime
> >>> from datetime import datetime
> >>> py_dt = datetime(2020, 8, 12)
> >>> j_dt = jdatetime.datetime(2020, 8, 12)
> >>> n_dt = np.datetime64('2020-08-12')
> >>> py_dt
> datetime.datetime(2020, 8, 12, 0, 0)
> >>> j_dt
> jdatetime.datetime(2020, 8, 12, 0, 0)
> >>> n_dt
> numpy.datetime64('2020-08-12')
> >>> np.array([py_dt], dtype='datetime64')
> array(['2020-08-12T00:00:00.000000'], dtype='datetime64[us]')
> >>> np.array([n_dt], dtype='datetime64')
> array(['2020-08-12'], dtype='datetime64[D]')
> >>> np.array([j_dt], dtype='datetime64')
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
> TypeError: Cannot cast datetime.datetime object from metadata [us] to  according to the rule 'same_kind'
> >>> np.array(['2020-08-12'], dtype='datetime64')
> array(['2020-08-12'], dtype='datetime64[D]')
> ```
> 
> 1. Can you please confirm if this is the root cause?
> 2. In your example, if you use a list of `datetime.datetime` instead of `jdatetime.datetime`, would that prevent the reported error?
> 
> Also please note that in any kind of issue reporting, it's helpful to mention runtime details, like Python version, the platform (OS, arch), and version of related libraries (numpy, etc.), specially if the results could be different for those differences.

**1:** Yes, the problem is that `matplotlib` only accepts `numpy.datetime64`. So, I cannot pass ` `jdatetime` object to it's `x-axis`.

**2:** Yes. Firstly, I draw the plot using `Georgian` DateTime values. But I want to show dates in `jalali`, and especially I want to show abbreviated month names in `Persian`, such as, `فرو` or `اردیب`, or even the full month names, such as `فروردین` or `اردیبهشت`.

**The version of python and libraries**
Operating system: ubuntu 18.04
Python version:3.6.9
jdatetime = 3.6.2
Matplotlib version = 3.3.0
numpy = 1.18.1
pandas = 1.1.0
PyQt5 = 5.15.0

I also tested if the problem is persistent in (Ubuntu for ARM 20.04), and it occurred there too.

**Comment by slashmili** [comment]
Thanks @minaee for reporting this.

As you found out, we are not compatible with Matplotlib!

Our main goal is to be compatible with Python's datetime module and looks like [datetime64](https://numpy.org/doc/stable/reference/arrays.datetime.html) is a totally different beast.

What do you think @farzadghanei,  @hramezani , @mehdisadeghi

**Comment by mehdisadeghi** [comment]
>This basic example shows that numpy can create an array from a list of strings, datetime.datetime, and numpy.datetime64 objects, however it can not create an array from a list of jdatetime.datetime objects.

If you skip the dtype it will create simple an array of jdatetime as simple objects. However, it is not useful for OP most probably.

> the problem is that matplotlib only accepts numpy.datetime64. So, I cannot pass jdatetime object to it's x-axis.
> As you found out, we are not compatible with Matplotlib!

This doesn't solve the datetime64 incompatibility problem but works for me:

```
import numpy as np
import jdatetime
import locale
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

jarray = np.array([jdatetime.datetime.now(), jdatetime.datetime.now(), jdatetime.datetime.now()])
jdata = np.array([1,2,3])

locale.setlocale(locale.LC_ALL, "fa_IR") 
formatter = mdates.DateFormatter("%a, %d %b") 
ax = plt.gca()
ax.xaxis.set_major_formatter(formatter)

plt.plot_date(jarray, jdata) 
plt.show()
```

**Comment by farzadghanei** [comment]
@minaee my questions were to help clarify the issue, so we can decide if this is related to this project at all, and if so, how to fix it. I'm afraid I didn't get the answers right.

The answers:

> 1: Yes, the problem is that matplotlib only accepts numpy.datetime64. So, I cannot pass jdatetime object to it's x-axis.

> 2: Yes. Firstly, I draw the plot using Georgian DateTime values. But I want to show dates in jalali, and especially I want to show abbreviated month names in Persian, such as, فرو or اردیب, or even the full month names, such as فروردین or اردیبهشت.

I understand you want to use `matplotlib` to plot jalali dates, but because we don't have access to your code, and clearly some context is missing here, we have to use the shared information to find the problem. The actual problem, not just the one in your specific application.

1. My first question was if the root cause is `numpy.asarray`. I have explained this in details below.

2. If `matplotlib` only accepts `numpy.datetime64`, then does it mean `datetime.datetime` can't be directly used? did you have to convert to `numpy.datetime64` instances? The answer to this question is important, because `jdatetime` is not supposed to work with every Python datetime library out there. It only provides the same API as Python `datetime.datetime`. As @slashmili explained, `numpy.datetime64` is a totally different thing, and `jdatetime` is not compatible with that.


Now back to the first question, the root cause. The shared exception trace in the issue description, suggests the issue is with `numpy`. Because it says:

```python
self.canvas.axes.scatter(df_day.index.values, df_day.loc[:, item], linestyle="None", marker='.')
File "/home/shahriar/.local/lib/python3.6/site-packages/matplotlib/init.py", line 1565, in inner
return func(ax, *map(sanitize_sequence, args), **kwargs)
...
Collection.init(self, **kwargs)
File "/home/shahriar/.local/lib/python3.6/site-packages/matplotlib/collections.py", line 153, in init
offsets = np.asanyarray(offsets, float)  # <--- look at here
```

Which means `matplotlib` [is calling](https://github.com/matplotlib/matplotlib/blob/v3.3.0/lib/matplotlib/collections.py#L202) `numpy.asanarray()`.

The last lines of the trace say:

```python
File "/usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py", line 138, in asanyarray
return array(a, dtype, copy=False, order=order, subok=True)
TypeError: float() argument must be a string or a number, not 'datetime'
```

Which is [asanyarray()](https://github.com/numpy/numpy/blob/91118b3363b636f932f7ff6748d8259e9eb2c23a/numpy/core/_asarray.py#L138) function from `numpy`.

**Comment by farzadghanei** [comment]
> Our main goal is to be compatible with Python's datetime module and looks like datetime64 is a totally different beast.

@slashmili I agree, being compatible with every date and time library is not feasible. If a library accepts and treats Python `datetime` objects specifically, we can't guarantee to be supported by it. For example, here `numpy.asarray` accepts lists of `datetime.datetime`, but probably is explicitly checking for the the data type.

**Comment by minaee** [comment]
> @minaee my questions were to help clarify the issue, so we can decide if this is related to this project at all, and if so, how to fix it. I'm afraid I didn't get the answers right.
> 
> The answers:
> 
> > 1: Yes, the problem is that matplotlib only accepts numpy.datetime64. So, I cannot pass jdatetime object to it's x-axis.
> 
> > 2: Yes. Firstly, I draw the plot using Georgian DateTime values. But I want to show dates in jalali, and especially I want to show abbreviated month names in Persian, such as, فرو or اردیب, or even the full month names, such as فروردین or اردیبهشت.
> 
> I understand you want to use `matplotlib` to plot jalali dates, but because we don't have access to your code, and clearly some context is missing here, we have to use the shared information to find the problem. The actual problem, not just the one in your specific application.
> 
> 1. My first question was if the root cause is `numpy.asarray`. I have explained this in details below.
> 2. If `matplotlib` only accepts `numpy.datetime64`, then does it mean `datetime.datetime` can't be directly used? did you have to convert to `numpy.datetime64` instances? The answer to this question is important, because `jdatetime` is not supposed to work with every Python datetime library out there. It only provides the same API as Python `datetime.datetime`. As @slashmili explained, `numpy.datetime64` is a totally different thing, and `jdatetime` is not compatible with that.
> 
> Now back to the first question, the root cause. The shared exception trace in the issue description, suggests the issue is with `numpy`. Because it says:
> 
> ```python
> self.canvas.axes.scatter(df_day.index.values, df_day.loc[:, item], linestyle="None", marker='.')
> File "/home/shahriar/.local/lib/python3.6/site-packages/matplotlib/init.py", line 1565, in inner
> return func(ax, *map(sanitize_sequence, args), **kwargs)
> ...
> Collection.init(self, **kwargs)
> File "/home/shahriar/.local/lib/python3.6/site-packages/matplotlib/collections.py", line 153, in init
> offsets = np.asanyarray(offsets, float)  # <--- look at here
> ```
> 
> Which means `matplotlib` [is calling](https://github.com/matplotlib/matplotlib/blob/v3.3.0/lib/matplotlib/collections.py#L202) `numpy.asanarray()`.
> 
> The last lines of the trace say:
> 
> ```python
> File "/usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py", line 138, in asanyarray
> return array(a, dtype, copy=False, order=order, subok=True)
> TypeError: float() argument must be a string or a number, not 'datetime'
> ```
> 
> Which is [asanyarray()](https://github.com/numpy/numpy/blob/91118b3363b636f932f7ff6748d8259e9eb2c23a/numpy/core/_asarray.py#L138) function from `numpy`.

ok, maybe my answers were not clear enough.

 1- Yes, the root cause is that Numpy doesn't accept `jdatetime` to convert it to `datetime64`. 

 2- I compare passing `datetime` (which is in Georgian) and `jdatetime` (which is in Jalali) to `scatter` function. 

I pass `datetime` to `scatter` function as following:
    
    self.canvas.axes.scatter(df_day.index.values, df_day.loc[:, item], linestyle="None", marker='.')

The content of and type of index of my `dataframe`:
 
    print("df_day.index type: \n", type(df_day.index))
    print("df_day.index: \n", df_day.index)

> df_day.index type: 
>  <class 'pandas.core.indexes.datetimes.DatetimeIndex'>
> df_day.index: 
>  DatetimeIndex(['2018-06-03 10:59:00', '2018-06-03 11:01:00',
>                '2018-06-03 11:02:00', '2018-06-03 11:03:00',
>                '2018-06-03 11:04:00', '2018-06-03 11:05:00',
>                '2018-06-03 11:06:00', '2018-06-03 11:08:00',
>                '2018-06-03 11:09:00', '2018-06-03 11:10:00',
>                ...
>                '2018-06-04 10:39:00', '2018-06-04 10:40:00',
>                '2018-06-04 10:42:00', '2018-06-04 10:43:00',
>                '2018-06-04 10:44:00', '2018-06-04 10:45:00',
>                '2018-06-04 10:46:00', '2018-06-04 10:47:00',
>                '2018-06-04 10:49:00', '2018-06-04 10:50:00'],
>               dtype='datetime64[ns]', name='Timestamp', length=1227, freq=None)

    print("df_day.index.values type: \n", type(df_day.index.values))
    print("df_day.index.values: \n", df_day.index.values)

> df_day.index.values type: 
>  <class 'numpy.ndarray'>
> df_day.index.values: 
>  ['2018-06-03T10:59:00.000000000' '2018-06-03T11:01:00.000000000'
>  '2018-06-03T11:02:00.000000000' ... '2018-06-04T10:47:00.000000000'
>  '2018-06-04T10:49:00.000000000' '2018-06-04T10:50:00.000000000']

    print("df_day.index.values[0] type: \n", type(df_day.index.values[0]))
    print("df_day.index.values[0]: \n", df_day.index.values[0])

> df_day.index.values[0] type: 
>  <class 'numpy.datetime64'>
> df_day.index.values[0]: 
>  2018-06-03T10:59:00.000000000

Up to this point, the code would run with no error and the plot is drawn as expected. The problem rise when I pass `jdatetime` as following:

    print("df_day.index type: \n", type(df_day.index))
    print("df_day.index: \n", df_day.index)

> df_day.index type: 
>  <class 'pandas.core.indexes.base.Index'>
> df_day.index: 
>  Index([1397-03-13 10:59:00, 1397-03-13 11:01:00, 1397-03-13 11:02:00,
>        1397-03-13 11:03:00, 1397-03-13 11:04:00, 1397-03-13 11:05:00,
>        1397-03-13 11:06:00, 1397-03-13 11:08:00, 1397-03-13 11:09:00,
>        1397-03-13 11:10:00,
>        ...
>        1397-03-14 10:39:00, 1397-03-14 10:40:00, 1397-03-14 10:42:00,
>        1397-03-14 10:43:00, 1397-03-14 10:44:00, 1397-03-14 10:45:00,
>        1397-03-14 10:46:00, 1397-03-14 10:47:00, 1397-03-14 10:49:00,
>        1397-03-14 10:50:00],
>       dtype='object', name='Timestamp', length=1227)

    print("df_day.index.values type: \n", type(df_day.index.values))
    print("df_day.index.values: \n", df_day.index.values)

> df_day.index.values type: 
>  <class 'numpy.ndarray'>
> df_day.index.values: 
>  [jdatetime.datetime(1397, 3, 13, 10, 59)
>  jdatetime.datetime(1397, 3, 13, 11, 1)
>  jdatetime.datetime(1397, 3, 13, 11, 2) ...
>  jdatetime.datetime(1397, 3, 14, 10, 47)
>  jdatetime.datetime(1397, 3, 14, 10, 49)
>  jdatetime.datetime(1397, 3, 14, 10, 50)]

    print("df_day.index.values[0] type: \n", type(df_day.index.values[0]))
    print("df_day.index.values[0]: \n", df_day.index.values[0])

> df_day.index.values[0] type: 
>  <class 'jdatetime.datetime'>
> df_day.index.values[0]: 
>  1397-03-13 10:59:00

And I get this error:

> Traceback (most recent call last):
>   File "/home/shahriar/python_projects/DataVisualization/test.py", line 1750, in <module>
>     ex = App()
>   File "/home/shahriar/python_projects/DataVisualization/test.py", line 42, in __init__
>     self.tab_widget = MyTabWidget(self)
>   File "/home/shahriar/python_projects/DataVisualization/test.py", line 277, in __init__
>     self.filterlastday()
>   File "/home/shahriar/python_projects/DataVisualization/test.py", line 1352, in filterlastday
>     self.canvas.axes.scatter(df_day.index.values, df_day.loc[:, item], linestyle="None", marker='.')
>   File "/home/shahriar/.local/lib/python3.6/site-packages/matplotlib/__init__.py", line 1565, in inner
>     return func(ax, *map(sanitize_sequence, args), **kwargs)
>   File "/home/shahriar/.local/lib/python3.6/site-packages/matplotlib/cbook/deprecation.py", line 358, in wrapper
>     return func(*args, **kwargs)
>   File "/home/shahriar/.local/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 4440, in scatter
>     alpha=alpha
>   File "/home/shahriar/.local/lib/python3.6/site-packages/matplotlib/collections.py", line 911, in __init__
>     Collection.__init__(self, **kwargs)
>   File "/home/shahriar/.local/lib/python3.6/site-packages/matplotlib/collections.py", line 153, in __init__
>     offsets = np.asanyarray(offsets, float)
>   File "/usr/local/lib/python3.6/dist-packages/numpy/core/_asarray.py", line 138, in asanyarray
>     return array(a, dtype, copy=False, order=order, subok=True)
> TypeError: float() argument must be a string or a number, not 'datetime'

>  2- If matplotlib only accepts numpy.datetime64, then does it mean datetime.datetime can't be directly used? did you have to convert to numpy.datetime64 instances? The answer to this question is important, because jdatetime is not supposed to work with every Python datetime library out there. It only provides the same API as Python datetime.datetime. As @slashmili explained, numpy.datetime64 is a totally different thing, and jdatetime is not compatible with that.

I directly pass `datetime` to `matplotlib`, and the `matplotlib` converts it to `Numpy.datetime64` itself. This means I didn't converted them to numpy.datetime64 instances, matplotlib did.

**Comment by minaee** [comment]
> > This basic example shows that numpy can create an array from a list of strings, datetime.datetime, and numpy.datetime64 objects, however it can not create an array from a list of jdatetime.datetime objects.
> 
> If you skip the dtype it will create an array of jdatetimes as simple objects. However, it is not useful for OP most probably.
> 
> > the problem is that matplotlib only accepts numpy.datetime64. So, I cannot pass jdatetime object to it's x-axis.
> > As you found out, we are not compatible with Matplotlib!
> 
> This doesn't solve the datetime64 incompatibility problem but works for me:
> 
> ```
> import numpy as np
> import jdatetime
> import locale
> import matplotlib.pyplot as plt
> import matplotlib.dates as mdates
> 
> jarray = np.array([jdatetime.datetime.now(), jdatetime.datetime.now(), jdatetime.datetime.now()])
> jdata = np.array([1,2,3])
> 
> locale.setlocale(locale.LC_ALL, "fa_IR") 
> formatter = mdates.DateFormatter("%a, %d %b") 
> ax = plt.gca()
> ax.xaxis.set_major_formatter(formatter)
> 
> plt.plot_date(jarray, jdata) 
> plt.show()
> ```

Sorry I cannot run your example code:

> Traceback (most recent call last):
>   File "/home/shahriar/.local/lib/python3.6/site-packages/matplotlib/axis.py", line 1573, in convert_units
>     ret = self.converter.convert(x, self.units, self)
>   File "/home/shahriar/.local/lib/python3.6/site-packages/matplotlib/dates.py", line 1921, in convert
>     return date2num(value)
>   File "/home/shahriar/.local/lib/python3.6/site-packages/matplotlib/dates.py", line 437, in date2num
>     return _to_ordinalf_np_vectorized(d)
>   File "/usr/local/lib/python3.6/dist-packages/numpy/lib/function_base.py", line 2091, in __call__
>     return self._vectorize_call(func=func, args=vargs)
>   File "/usr/local/lib/python3.6/dist-packages/numpy/lib/function_base.py", line 2161, in _vectorize_call
>     ufunc, otypes = self._get_ufunc_and_otypes(func=func, args=args)
>   File "/usr/local/lib/python3.6/dist-packages/numpy/lib/function_base.py", line 2121, in _get_ufunc_and_otypes
>     outputs = func(*inputs)
>   File "/home/shahriar/.local/lib/python3.6/site-packages/matplotlib/dates.py", line 230, in _to_ordinalf
>     rdt = datetime.datetime.combine(cdate, midnight_time)
> TypeError: combine() argument 1 must be datetime.date, not date
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/home/shahriar/python_projects/DataVisualization/notepad.py", line 15, in <module>
>     plt.plot_date(jarray, jdata)
>   File "/home/shahriar/.local/lib/python3.6/site-packages/matplotlib/pyplot.py", line 2773, in plot_date
>     data} if data is not None else {}), **kwargs)
>   File "/home/shahriar/.local/lib/python3.6/site-packages/matplotlib/__init__.py", line 1565, in inner
>     return func(ax, *map(sanitize_sequence, args), **kwargs)
>   File "/home/shahriar/.local/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 1721, in plot_date
>     ret = self.plot(x, y, fmt, **kwargs)
>   File "/home/shahriar/.local/lib/python3.6/site-packages/matplotlib/axes/_axes.py", line 1649, in plot
>     self.add_line(line)
>   File "/home/shahriar/.local/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 1850, in add_line
>     self._update_line_limits(line)
>   File "/home/shahriar/.local/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 1872, in _update_line_limits
>     path = line.get_path()
>   File "/home/shahriar/.local/lib/python3.6/site-packages/matplotlib/lines.py", line 1027, in get_path
>     self.recache()
>   File "/home/shahriar/.local/lib/python3.6/site-packages/matplotlib/lines.py", line 669, in recache
>     xconv = self.convert_xunits(self._xorig)
>   File "/home/shahriar/.local/lib/python3.6/site-packages/matplotlib/artist.py", line 178, in convert_xunits
>     return ax.xaxis.convert_units(x)
>   File "/home/shahriar/.local/lib/python3.6/site-packages/matplotlib/axis.py", line 1576, in convert_units
>     f'units: {x!r}') from e
> matplotlib.units.ConversionError: Failed to convert value(s) to axis units: array([jdatetime.datetime(1399, 5, 25, 9, 12, 4, 93255),
>        jdatetime.datetime(1399, 5, 25, 9, 12, 4, 93356),
>        jdatetime.datetime(1399, 5, 25, 9, 12, 4, 93398)], dtype=object)
> 
> Process finished with exit code 1
>

**Comment by slashmili** [comment]
I'm going to close this issue due to inactivity
