### ISSUE TITLE
changing locale in python 3

### ISSUE THREAD

**Issue by hamedf62** [slashmili/python-jalali#70]
hi @yassersouri 
thank you for the great module!

unfortunately in python3 even when changing local to FA the result returned in english.

any advise?

**Comment by farzadghanei** [comment]
@hamedf62 could you please share a code snippet of the mentioned issue, and make it clear how the output is different than the expectation?

Also please include your runtime information (system, exact Python version and `jdatetime` version).

**Comment by hamedf62** [comment]
thank you @farzadghanei 

Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 10:41:24) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import locale
>>> import jdatetime
>>> locale.setlocale(locale.LC_ALL, "fa_IR")
'fa_IR'
>>> jdatetime.datetime.now().strftime("%a, %d %b %Y %H:%M:%S")
'Thu, 30 Mor 1399 11:26:38'


Name: jdatetime
Version: 3.6.2
Summary: Jalali datetime binding for python
Home-page: https://github.com/slashmili/python-jalali
Author: Milad Rastian
Author-email: eslashmili@gmail.com
License: Python Software Foundation License
Location: c:\users\hamed\pycharmprojects\untitled1\venv\lib\site-packages
Requires:
Required-by:

Python 3.7.7

**Comment by slashmili** [comment]
@hamedf62 Hi 👋 

That's strange, the test passes in [python 3.7(win)](https://ci.appveyor.com/project/slashmili/python-jalali/builds/34756947/job/aqms8rsl5c4t283y).

Could you clone the repo and run the unit test in your machine and give me the output?

```
git clone <repo>
cd <repo>
python.exe t/test.py
```

**Comment by hamedf62** [comment]
> @hamedf62 Hi 👋
> 
> That's strange, the test passes in [python 3.7(win)](https://ci.appveyor.com/project/slashmili/python-jalali/builds/34756947/job/aqms8rsl5c4t283y).
> 
> Could you clone the repo and run the unit test in your machine and give me the output?
> 
> ```
> git clone <repo>
> cd <repo>
> python.exe t/test.py
> ```

@slashmili greetings!
miss you for long time... wish all going well with you!

actually you right and all related to my locale to get Farsi charachters. all working perfectly with Jdatetime

also there is another issue with converting two digit year to jdatetime format. kindly check below script:

jdatetime.datetime.strptime('99',"%y")

it return ValueError.

have fun

**Comment by slashmili** [comment]
@hamedf62 Prefect!

As for the strptime problem, could please open another issue.
