### ISSUE TITLE
Upload wheel to pypi

### ISSUE THREAD

**Issue by rth** [slashmili/python-jalali#74]
It could be useful to upload a wheel of this package to PyPi. The lack of a wheel there makes  installation slightly slower and is a blocker for using this package with [pyodide](https://github.com/iodide-project/pyodide).

**Comment by slashmili** [comment]
Sure!

I'm not much familiar with that but will make a new release with the wheel support

**Comment by slashmili** [comment]
@rth I've finally managed to make the `wheel` package work! the latest version `3.6.4` also has `whl` file: https://pypi.org/project/jdatetime/3.6.4/#files

**Comment by rth** [comment]
Thanks @slashmili !
