### ISSUE TITLE
isleap function

### ISSUE THREAD

**Issue by BardiaMGTGC** [slashmili/python-jalali#78]
hey
so i was using this library and testing different functions
but i cant get isleap to work

can you give me a syntax example?
i have tried: 
jdatetime.datetime.isleap(1395)
jdatetime.date.isleap(1395)
jdatetime.datetime().isleap(1395)
jdatetime.date().isleap(1395)
jdatetime.datetime(1395).isleap()
jdatetime.date(1395).isleap()
thanks

**Comment by hramezani** [comment]
Hey,

You can check it like:

```python
kabiseh_year = jdatetime.date(1391, 12, 30)
kabiseh_year.isleap()
```

**Comment by BardiaMGTGC** [comment]
thanks
