### ISSUE TITLE
Publishing the package to pypi as part of GitHubAction

### ISSUE THREAD

**Issue by slashmili** [slashmili/python-jalali#80]
the build commands fails in [Github Action
](https://github.com/slashmili/python-jalali/runs/2209305160?check_suite_focus=true#step:5:17)

```
python setup.py sdist bdist_wheel
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help
error: invalid command 'bdist_wheel'
```

I have the same experience in my Mac the problem is `bdist_wheel` option

I thought installing `wheel` does the trick

https://github.com/slashmili/python-jalali/blob/main/.github/workflows/python-publish.yml#L22-L25

But for some reason `bdist_wheel` doesn't work 🤷 

Any idea @farzadghanei ?

**Comment by farzadghanei** [comment]
maybe the installation step to install wheel could be:

```
python -m pip install setuptools wheel twine
```
to make sure the same `pip` is installing `wheel`?

**Comment by slashmili** [comment]
I've managed to fix it and it's extremely unusual 🤨 

https://github.com/slashmili/python-jalali/commit/6d1bd094cb7a322bda673c2d5af2c25e308152e0
