### ISSUE TITLE
v3.6.2 release got overwritten by releasing v3.6.3 under the same tag

### ISSUE THREAD

**Issue by suntorytimed** [slashmili/python-jalali#81]
The release of v3.6.3 13 days ago has overwritten the v3.6.2 release and tag, as the name was set wrong:

https://github.com/slashmili/python-jalali/releases/tag/v3.6.2

We stumbled upon this when packaging python-jdatetime on openSUSE, as the v3.6.2 tarball used in that package is not matching the upstream provided one when doing the source check.

Could you please fix the tag and release again, so that v3.6.2 is available with the correct git commit hash?

**Comment by farzadghanei** [comment]
@slashmili release related

**Comment by slashmili** [comment]
Oops, very sorry about that. I somehow missed this message as well 🤦 

fixed it https://github.com/slashmili/python-jalali/releases/tag/v3.6.2
