### ISSUE TITLE
problem to convert from string to time

### ISSUE THREAD

**Issue by hojati** [slashmili/python-jalali#82]
* jdatetime version: 3.6.2
* Python version: 3.8
* OS: Windows

<div dir="rtl">
سلام
وقتی می خوام یک رشته به فرمت
%d %B %Y
رو تبدیل به فرمت 
datetime
کنم پیغام ذیل نمایش داده میشه:
</div>

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "...\lib\site-packages\jdatetime\__init__.py", line 927, in strptime
    raise ValueError(
ValueError: time data '14 Khordad 1400' does not match format '%d %B %Y'
```

<div dir="rtl">
کد رو که نگاه میکنم به نظر میرسه اصلا برای 
%B
هیچ مپی وجود نداره 
راه حل چیست ؟
ممنون
</div>

**Comment by hramezani** [comment]
Hi @hojati, Thanks for reporting.
Yes, `jdatetime.datetime.strptime('14 Khordad 1400', '%d %B %Y')` throws error because `jdatetime.datetime.strptime` doesn't handle `%B` and `%b`.

The solution would be to implement it. Would you like to do it?

**Comment by hojati** [comment]
sorry, maybe sometime else but it is better to solve this issue in future for this helpful package. I solved my own problem by manually replace Persian month to number and then convert it to datetime.

**Comment by slashmili** [comment]
Thanks @hojati for reporting the issue.

created a feature support ticket #91
