### ISSUE TITLE
printing literal %s

### ISSUE THREAD

**Issue by davoudarsalani** [slashmili/python-jalali#83]
I was trying different formats and I found that ```print(jdatetime.datetime.now().strftime("%s"))``` prints literal `%s` instead of `1620108348`.

* jdatetime version: 3.6.2
* Python version: 3.9.2
* OS: Arch Linux

**Comment by farzadghanei** [comment]
@davoudarsalani thanks for your interest in the project. `%s` is not implemented as a [format code](https://github.com/slashmili/python-jalali/blob/455dfda2a74a2afa874146f13f86fa22c97e5191/jdatetime/__init__.py#L541) in jdatetime.

It doesn't seem to be a documented format code in standard library:

- https://docs.python.org/3/library/datetime.html#strftime-and-strptime-format-codes
- https://docs.python.org/3/library/time.html#time.strftime

If a Unix timestamp is needed, the [timestamp](https://github.com/slashmili/python-jalali/blob/455dfda2a74a2afa874146f13f86fa22c97e5191/jdatetime/__init__.py#L874) method provides the value:

```
>>> jdatetime.datetime.now().timestamp()
1620135794.377304
```
