### ISSUE TITLE
__add__ and __sub__ should return NotImplemented

### ISSUE THREAD

**Issue by saber-solooki** [slashmili/python-jalali#84]
You should return NotImplemented in arithmetic operations. Suppose I am using a library and the object of a class in this library knows how to do arithmetic operations and this object is the right object of arithmetic operations. (suppose this expression: a + b. "a" is an instance of `jdatetime` and "b" is the object of my library). When you raise an exception, the interpreter cannot reach to __radd__ method of the object of the class in my library("b" in my example).

Related links:
[NotImplemented](https://docs.python.org/3/reference/datamodel.html#the-standard-type-hierarchy)
[Implementing the arithmetic operations](https://docs.python.org/3/library/numbers.html#implementing-the-arithmetic-operations)

* jdatetime version:3.6.0
* Python version:3.9
* OS: ubuntu

**Comment by farzadghanei** [comment]
```
$ python
Python 3.9.5 (default, May 14 2021, 00:00:00) 
[GCC 10.3.1 20210422 (Red Hat 10.3.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from datetime import datetime
>>> now = datetime.now()
>>> now
datetime.datetime(2021, 7, 2, 8, 59, 41, 891375)
>>> now + 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'datetime.datetime' and 'int'
>>> 
```
python's [datetime](https://docs.python.org/3/library/datetime.html) raises an error. this project [aims](https://github.com/slashmili/python-jalali#jdatetime) to be as compatible as possible:

> jdatetime is Jalali implementation of Python's datetime module

with some extra functionality for local/calendar reasons only.
I don't think this library needs to implement the proposed behavior here, as that behavior is designed for [numeric types](https://docs.python.org/3/library/numbers.html#the-numeric-tower). Not every type is a number.

**Comment by saber-solooki** [comment]
You get raised exception because numeric types also don't know how to perform + operand. If you pay more attention to my example, "b" which is an object of a specific class (not the object of numeric types) that knows how to perform arithmetic operations of a `datetime` object, cannot do its duty because you already raise an exception. Besides if you read my mentioned links carefully (I mentioned bellow):

> If A falls back to the boilerplate code, and it were to return a value from __add__(), we’d miss the possibility that B defines a more intelligent __radd__(), so the boilerplate should return NotImplemented from __add__(). (Or A may not implement __add__() at all.)

 the python document emphasizes returning NotImpelmented when you don't know how to perform the arithmetic operations, not raising `TypeError`.

**Comment by farzadghanei** [comment]
@saber-solooki you're right, the standard library datetime module [does return](https://github.com/python/cpython/blob/943e77d42d3f84b581f32c05f1fc8c05366b8ed3/Lib/datetime.py#L1041) `NotImplemented`

```
>>> import datetime
>>> datetime.datetime.now().__add__('foo')
NotImplemented
```
 Maybe you're interested in making a PR for this?

**Comment by saber-solooki** [comment]
I give you this example. Look at [this](https://github.com/celery/celery/blob/master/celery/utils/time.py#L175) line of celery library. `start` parameter is an instance of `datetime` and `ends_in` is an instance of [ffwd class](https://github.com/celery/celery/blob/master/celery/utils/time.py#L318). As you see `ffwd` class implement `__radd__` function. `datetime` doesn't know how to add `ffwd` object to `datetime` and return `NotImpelemted` but `ffwd` object knows how to add `datetime` object to itself which implemented in `__radd__`. Because you raise an exception in `__add__` function of `jdatetime`, `ffwd` object doesn't get a chance to try its implementation.

**Comment by saber-solooki** [comment]
I will be glad to make o PR for this. Thank's

**Comment by farzadghanei** [comment]
Yes, current behavior of `jdatetime` (raising) differs that of stdlib `datetime` (returning), so a PR to make it right is more than welcome, thanks.

As a side note, about the celery example you sent, if an application is using `jdatetime` with celery and it reaches there and fails because of this difference, implementing it won't solve the issue, because `ffwd` [only accepts `datetime.date` objects](https://github.com/celery/celery/blob/c33e9b2a6905a239c45e6f50437394db69fa41db/celery/utils/time.py#L343), which `jdatetime` [is not](https://github.com/slashmili/python-jalali/blob/455dfda2a74a2afa874146f13f86fa22c97e5191/jdatetime/__init__.py#L111).

so I think the solution for that particular problem, is to convert the `jdatetime` instance to a `datetime` when working with celery.

**Comment by saber-solooki** [comment]
Yes, you are right. I don't know what is your reason to not inherit from `datetime`. I handled mentioned problem with a trick
