### ISSUE TITLE
Support %B directive  for strptime

### ISSUE THREAD

**Issue by slashmili** [slashmili/python-jalali#91]
We want to support `%B` and `%b` directive in strptime function:

This directive  is supported in `datetime` module:
```python
>>> import datetime
>>> datetime.datetime.strptime('14 September 2021', "%d %B %Y")
datetime.datetime(2021, 9, 14, 0, 0)
```

Expected behaviour:
```python
jdatetime.datetime.strptime('14 Khordad 1400', '%d %B %Y')
jdatetime.datetime(1400, 3, 14, 0, 0)
```

Open questions:
* How should we support this directive considering different possible locale?

**Comment by Mojtaba-saf** [comment]
to clarify by different locale you mean it should also behave like this?

```
jdatetime.datetime.strptime('14 خرداد 1400', '%d %B %Y')
jdatetime.datetime(1400, 3, 14, 0, 0)
```
it meant to be "day j_month year" but persian name was moved to last in editor

**Comment by slashmili** [comment]
the `strptime` is flexible enough to move the parts around. 

the request should be : 
```python
jdatetime.datetime.strptime('۱۴ خرداد ۱۴۰۰', '%d %B %Y') # the string is in : day month-name year

jdatetime.datetime.strptime('14 Khordad 1400, "%d %B %Y")
```

My question was if we should support mix of English and Persian chars like:
```python
jdatetime.datetime.strptime('14 خرداد 1400', '%d %B %Y')
```
And if yes, how would it be implemented?

**Comment by Mojtaba-saf** [comment]
I think python 3 can cast Unicode numbers to integer.
```
int("۱۴")=14
int("1۴")=14
```
but current regex patterns won't detect Persian numbers.
I propose we change the patterns to something like this to detect Persian and ASCII numbers.

```
_DIRECTIVE_PATTERNS = {
    '%Y': '(?P<Y>[0-9\u06F0-\u06F9]{4})',
    '%y': '(?P<y>[0-9\u06F0-\u06F9]{2})',
    '%m': '(?P<m>[0-9\u06F0-\u06F9]{1,2})',
    '%d': '(?P<d>[0-9\u06F0-\u06F9]{1,2})',
    '%H': '(?P<H>[0-9\u06F0-\u06F9]{1,2})',
    '%M': '(?P<M>[0-9\u06F0-\u06F9]{1,2})',
    '%S': '(?P<S>[0-9\u06F0-\u06F9]{1,2})',
    '%f': '(?P<f>[0-9\u06F0-\u06F9]{1,6})',
}
```

with this pattern it can detect any combination of numbers for example all of these now are acceptable.
```
"1400"
"۱۴۰۰"
"۱۴01"
```
we do the same for %B. pattern below detects all en_j_months pattern:
`%B': '(?P<B>[a-zA-Z]{3,12})'`
so **Farvardin** and **farvardin** and **FaRvardin** will be detected.
we add the Unicode Persian characters to this pattern and now it detects Persian names as well.
```
_DIRECTIVE_PATTERNS = {
    '%Y': '(?P<Y>[0-9\u06F0-\u06F9]{4})',
    '%y': '(?P<y>[0-9\u06F0-\u06F9]{2})',
    '%m': '(?P<m>[0-9\u06F0-\u06F9]{1,2})',
    '%d': '(?P<d>[0-9\u06F0-\u06F9]{1,2})',
    '%H': '(?P<H>[0-9\u06F0-\u06F9]{1,2})',
    '%M': '(?P<M>[0-9\u06F0-\u06F9]{1,2})',
    '%S': '(?P<S>[0-9\u06F0-\u06F9]{1,2})',
    '%f': '(?P<f>[0-9\u06F0-\u06F9]{1,6})',
    '%B': '(?P<B>[a-zA-Z\u0600-\u06EF\uFB8A\u067E\u0686\u06AF]{3,12})',
    '%b': '(?P<b>[a-zA-Z]{3})',
}
```
now it can detect Persian words but we need to map these names to a number so after regex we try to detect if %b or %B is used and if it is used we check if its ASCII or not to use the list of month names in date class to map them to a number:

```
match = _re.match(regex + '$', date_string)
month = get('B') or get('b') or int(get('m', 1))
if isinstance(month, str):
            try:
                if get('b'):
                    month = date.j_month_short_to_num(name=month)
                elif month.isascii():
                    month = date.j_month_to_num(name=month)
                else:
                    month = date.j_months_fa_to_num(name=month)
            except ValueError:
                raise ValueError(
                    "time data '%s' does not match format '%s'" %
                    (date_string, format)
                )
```
this should work for all the instances below:
```
jdatetime.datetime.strptime('14 Khordad 1400, "%d %B %Y")
jdatetime.datetime.strptime('۱۴ Khordad ۱۴۰۰, "%d %B %Y")
jdatetime.datetime.strptime('۱۴ Khordad 1400, "%d %B %Y")
jdatetime.datetime.strptime('۱۴ خرداد ۱۴۰۰', '%d %B %Y') # the string is in : day month-name year
jdatetime.datetime.strptime('14 خرداد 1400', '%d %B %Y') # the string is in : day month-name year
jdatetime.datetime.strptime('1۴ خرداد 14۰0', '%d %B %Y') # the string is in : day month-name year
```
ps:
pattern to detect Persian month names could be optimized cause max length would be for "اردیبهشت" and it's 8 characters.

**Comment by Mojtaba-saf** [comment]
in python 3 we could even use '/d' instead of ['0-9\u06F0-\u06F9'] because /d detects Unicode Persian numbers but I think python 2.7 can't do the same.

**Comment by slashmili** [comment]
Deployed as part of [v4.1.0](https://github.com/slashmili/python-jalali/releases/tag/v4.1.0)
